name: interview-analysis-env
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=2.1.0
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - alsa-lib=1.2.13
  - aom=3.7.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - astunparse=1.6.3
  - async-lru=2.0.4
  - async-timeout=5.0.1
  - attr=2.5.1
  - attrs=24.3.0
  - babel=2.16.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.2.0
  - blinker=1.9.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - cached-property=1.5.2
  - cachetools=5.5.1
  - cairo=1.18.0
  - certifi=2025.1.31
  - cffi=1.17.1
  - click=8.1.7
  - comm=0.2.1
  - cryptography=44.0.1
  - cuda-crt-tools=12.4.131
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-cupti=12.4.127
  - cuda-nvcc-tools=12.4.131
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-nvvm-tools=12.4.131
  - cuda-version=12.4
  - cudnn=9.1.1.17
  - cyrus-sasl=2.1.27
  - dav1d=1.2.1
  - dbus=1.13.18
  - debugpy=1.8.11
  - defusedxml=0.7.1
  - eigen=3.4.0
  - executing=0.8.3
  - expat=2.6.4
  - flask=3.1.0
  - flatbuffers=23.5.26
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freeglut=3.4.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.5.0
  - gast=0.5.3
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.3.0
  - gnutls=3.7.9
  - google-auth=2.38.0
  - google-auth-oauthlib=0.5.2
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - grpcio=1.54.3
  - gst-plugins-base=1.22.9
  - gstreamer=1.22.9
  - gunicorn=23.0.0
  - h11=0.14.0
  - h5py=3.13.0
  - harfbuzz=8.3.0
  - hdf5=1.14.3
  - icu=73.2
  - imageio=2.37.0
  - imageio-ffmpeg=0.6.0
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.15.0
  - itsdangerous=2.2.0
  - jasper=4.2.4
  - jedi=0.19.2
  - joblib=1.4.2
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - leptonica=1.83.1
  - lerc=4.0.0
  - libabseil=20230125.3
  - libaec=1.1.3
  - libarchive=3.7.7
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libass=0.17.1
  - libblas=3.9.0
  - libcap=2.71
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcups=2.3.3
  - libcurand=10.3.5.147
  - libcurl=8.4.0
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.20
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.4
  - libflac=1.4.3
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.0
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgfortran-ng=8.2.0
  - libgfortran5=14.2.0
  - libglib=2.78.4
  - libglu=9.0.0
  - libgomp=14.2.0
  - libgpg-error=1.51
  - libgrpc=1.54.3
  - libiconv=1.18
  - libidn2=2.3.4
  - libjpeg-turbo=3.0.3
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libnghttp2=1.57.0
  - libntlm=1.6
  - libnvjitlink=12.4.127
  - libogg=1.3.5
  - libopenblas=0.3.21
  - libopencv=4.9.0
  - libopenvino=2023.2.0
  - libopenvino-auto-batch-plugin=2023.2.0
  - libopenvino-auto-plugin=2023.2.0
  - libopenvino-hetero-plugin=2023.2.0
  - libopenvino-intel-cpu-plugin=2023.2.0
  - libopenvino-intel-gpu-plugin=2023.2.0
  - libopenvino-ir-frontend=2023.2.0
  - libopenvino-onnx-frontend=2023.2.0
  - libopenvino-paddle-frontend=2023.2.0
  - libopenvino-pytorch-frontend=2023.2.0
  - libopenvino-tensorflow-frontend=2023.2.0
  - libopenvino-tensorflow-lite-frontend=2023.2.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.39
  - libpq=16.8
  - libprotobuf=3.21.12
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=256.9
  - libtasn1=4.19.0
  - libtheora=1.1.1
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.21.0
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.7.0
  - libxml2=2.13.5
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.6
  - mistune=3.1.2
  - ml_dtypes=0.4.0
  - moviepy=1.0.3
  - mpg123=1.32.9
  - multidict=6.1.0
  - mysql=5.7.20
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nccl=2.21.5.1
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - nltk=3.9.1
  - notebook=7.3.2
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.100
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - oauthlib=3.2.2
  - ocl-icd=2.3.2
  - ocl-icd-system=1.0.0
  - opencv=4.9.0
  - openh264=2.4.0
  - openjpeg=2.5.2
  - openldap=2.6.9
  - openssl=3.4.1
  - opt_einsum=3.3.0
  - overrides=7.4.0
  - p11-kit=0.24.1
  - packaging=24.2
  - pandas=2.1.4
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=25.0
  - pixman=0.44.2
  - platformdirs=3.10.0
  - proglog=0.1.10
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.43
  - propcache=0.2.0
  - protobuf=4.21.12
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pulseaudio-client=16.1
  - pure_eval=0.2.2
  - py-opencv=4.9.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pydub=0.25.1
  - pyjwt=2.10.1
  - pyopenssl=24.3.0
  - pysocks=1.7.1
  - python=3.9.21
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-flatbuffers=24.3.25
  - python-json-logger=3.2.1
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qt-main=5.15.8
  - re2=2023.03.02
  - readline=8.2
  - referencing=0.30.2
  - regex=2024.11.6
  - requests=2.32.3
  - requests-oauthlib=2.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - rsa=4.7.2
  - scikit-learn=1.1.3
  - scipy=1.8.1
  - send2trash=1.8.2
  - setuptools=75.8.0
  - six=1.16.0
  - snappy=1.1.10
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - svt-av1=1.8.0
  - tbb=2022.0.0
  - tensorboard=2.13.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.13.1
  - tensorflow-base=2.13.1
  - tensorflow-estimator=2.13.1
  - termcolor=2.1.0
  - terminado=0.17.1
  - tesseract=5.3.4
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.14
  - tomli=2.0.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2025a
  - urllib3=2.3.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - wrapt=1.17.0
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.42
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.12
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.18.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - annotated-types==0.7.0
      - anyio==4.8.0
      - assemblyai==0.37.0
      - charset-normalizer==3.4.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - decorator==5.2.1
      - exceptiongroup==1.2.2
      - facenet-pytorch==2.6.0
      - fer==22.5.1
      - ffmpeg==1.4
      - filelock==3.17.0
      - fonttools==4.56.0
      - fsspec==2025.3.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - idna==3.10
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - keras==3.9.0
      - kiwisolver==1.4.7
      - markdown-it-py==3.0.0
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - namex==0.0.8
      - networkx==3.2.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.1.105
      - opencv-contrib-python==4.11.0.86
      - optree==0.14.1
      - pillow==10.2.0
      - praat-parselmouth==0.4.5
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pyparsing==3.2.1
      - python-dotenv==1.0.1
      - sniffio==1.3.1
      - sympy==1.13.3
      - torch==2.2.2
      - torchvision==0.17.2
      - triton==2.2.0
      - websockets==15.0.1
