name: interview-analysis-env
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - altair=5.0.1
  - anyio=4.5.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - arrow-cpp=16.1.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=24.2.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - babel=2.16.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.1.0
  - blinker=1.6.2
  - boost-cpp=1.82.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.8.30
  - cffi=1.15.0
  - charset-normalizer=3.4.0
  - click=8.1.7
  - comm=0.2.2
  - contourpy=1.0.5
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - debugpy=1.6.7
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - flask=3.0.3
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - gflags=2.2.2
  - gitdb=4.0.7
  - gitpython=3.1.43
  - glib=2.78.4
  - glib-tools=2.78.4
  - glog=0.5.0
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.7
  - httpx=0.27.2
  - hyperframe=6.0.1
  - icu=73.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - importlib_resources=6.4.5
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.12.2
  - ipython_genutils=0.2.0
  - ipywidgets=7.8.1
  - isoduration=20.11.0
  - itsdangerous=2.2.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.12.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libgrpc=1.62.2
  - libiconv=1.16
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.5
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=2.1.1
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.7
  - mdurl=0.1.0
  - mistune=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mysql=8.4.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nltk=3.9.1
  - notebook=7.2.2
  - notebook-shim=0.2.4
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.0.16
  - orc=2.0.1
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.0.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - ply=3.11
  - pooch=1.7.0
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - psutil=5.9.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=16.1.0
  - pycparser=2.22
  - pydeck=0.8.0
  - pygments=2.18.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.8.20
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.8
  - pytz=2024.2
  - pyyaml=6.0
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.35.1
  - regex=2024.9.11
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.7.1
  - rpds-py=0.10.6
  - s2n=1.3.27
  - scikit-learn=1.1.3
  - scipy=1.10.1
  - seaborn=0.13.2
  - send2trash=1.8.3
  - setuptools=75.1.0
  - sip=6.7.12
  - six=1.16.0
  - smmap=4.0.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.6.2
  - streamlit=1.38.0
  - tbb=2021.8.0
  - tenacity=8.2.3
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.14
  - toml=0.10.2
  - tomli=2.0.2
  - toolz=0.12.0
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241003
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2025a
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.2.3
  - utf8proc=2.6.1
  - watchdog=4.0.1
  - wcwidth=0.2.13
  - webcolors=24.8.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - widgetsnbextension=3.6.6
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - annotated-types==0.7.0
      - assemblyai==0.37.0
      - astunparse==1.6.3
      - cachetools==5.5.2
      - decorator==4.4.2
      - facenet-pytorch==2.6.0
      - fer==22.5.1
      - ffmpeg==1.4
      - filelock==3.16.1
      - flatbuffers==25.2.10
      - fsspec==2025.3.0
      - gast==0.4.0
      - google-auth==2.38.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.70.0
      - h5py==3.11.0
      - imageio==2.35.1
      - imageio-ffmpeg==0.5.1
      - keras==2.13.1
      - keras-preprocessing==1.1.2
      - libclang==18.1.1
      - markdown==3.7
      - moviepy==1.0.3
      - mpmath==1.3.0
      - networkx==3.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - opencv-contrib-python==4.11.0.86
      - opt-einsum==3.4.0
      - pillow==10.2.0
      - praat-parselmouth==0.4.5
      - proglog==0.1.10
      - protobuf==4.25.6
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - speechrecognition==3.10.4
      - sympy==1.13.3
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.1
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.4.0
      - torch==2.2.2
      - torchvision==0.17.2
      - triton==2.2.0
      - websockets==13.1
      - werkzeug==3.0.6
      - wordcloud==1.9.4
      - wrapt==1.17.2
