name: posture-analysis-env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blinker=1.9.0
  - ca-certificates=2025.2.25
  - flask=3.1.0
  - itsdangerous=2.2.0
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - markupsafe=3.0.2
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.0
  - python=3.9.21
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - werkzeug=3.1.3
  - wheel=0.45.1
  - xz=5.6.4
  - zipp=3.21.0
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.5.0
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.8.0
      - async-timeout==4.0.3
      - attrs==25.1.0
      - beautifulsoup4==4.12.3
      - cachetools==5.5.2
      - category-encoders==2.6.3
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.3.0
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - eval-type-backport==0.2.2
      - exceptiongroup==1.2.2
      - filelock==3.17.0
      - flatbuffers==25.2.10
      - fonttools==4.56.0
      - fpdf==1.7.2
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - gensim==4.3.2
      - gitdb==4.0.12
      - gitpython==3.1.44
      - greenlet==3.1.1
      - gunicorn==23.0.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.29.2
      - idna==3.10
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - jax==0.4.30
      - jaxlib==0.4.30
      - jinja2==3.1.6
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.7
      - langchain==0.1.11
      - langchain-community==0.0.38
      - langchain-core==0.1.53
      - langchain-pinecone==0.1.1
      - langchain-text-splitters==0.0.2
      - langsmith==0.1.147
      - markdown-it-py==3.0.0
      - marshmallow==3.26.1
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - mediapipe==0.10.11
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - narwhals==1.30.0
      - networkx==3.2.1
      - nltk==3.8.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - opencv-contrib-python==4.11.0.86
      - opencv-python-headless==4.10.0.84
      - opt-einsum==3.4.0
      - orjson==3.10.15
      - packaging==23.2
      - pandas==2.2.1
      - patsy==1.0.1
      - pillow==10.4.0
      - pinecone-client==3.2.2
      - plotly==5.19.0
      - propcache==0.3.0
      - protobuf==3.20.3
      - pyarrow==19.0.1
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydeck==0.9.1
      - pygments==2.19.1
      - pyparsing==3.2.1
      - pypdf2==3.0.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2025.1
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - rpds-py==0.23.1
      - safetensors==0.5.3
      - scikit-learn==1.4.1.post1
      - scipy==1.13.1
      - seaborn==0.13.2
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.1.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sounddevice==0.5.1
      - soupsieve==2.6
      - sqlalchemy==2.0.38
      - statsmodels==0.14.4
      - streamlit==1.32.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==8.5.0
      - threadpoolctl==3.5.0
      - together==1.2.7
      - tokenizers==0.15.2
      - toml==0.10.2
      - torch==2.6.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - transformers==4.38.2
      - triton==3.2.0
      - typer==0.12.5
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - tzdata==2025.1
      - urllib3==2.3.0
      - watchdog==6.0.0
      - wrapt==1.17.2
      - xgboost==2.0.3
      - yarl==1.18.3
      - youtube-transcript-api==0.6.2
