name: posture-analysis-env
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _py-xgboost-mutex=2.0
  - aom=3.6.0
  - blas=1.0
  - blinker=1.9.0
  - blosc=1.21.3
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - cairo=1.16.0
  - category_encoders=2.6.3
  - click=8.1.7
  - cloudpickle=3.0.0
  - contourpy=1.2.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.13.18
  - dill=0.3.8
  - eigen=3.4.0
  - expat=2.6.4
  - ffmpeg=6.1.1
  - flask=3.1.0
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.12.1
  - future=1.0.0
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - graphite2=1.3.14
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gunicorn=23.0.0
  - harfbuzz=10.2.0
  - hdf5=1.14.5
  - hyperopt=0.2.7
  - icu=73.1
  - imbalanced-learn=0.12.3
  - importlib-metadata=8.5.0
  - importlib_resources=6.4.0
  - intel-openmp=2023.1.0
  - itsdangerous=2.2.0
  - jinja2=3.1.5
  - joblib=1.4.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - leptonica=1.82.0
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarchive=3.7.7
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.12.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=4.25.3
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libtheora=1.1.1
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxgboost=2.0.3
  - libxkbcommon=1.0.1
  - libxml2=2.13.5
  - lightgbm=4.5.0
  - llvmlite=0.43.0
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - miceforest=5.6.2
  - missingno=0.5.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mysql=8.4.0
  - ncurses=6.4
  - networkx=3.2.1
  - nltk=3.8.1
  - numba=0.60.0
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - opencv=4.10.0
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.0.16
  - packaging=24.2
  - pandas=2.2.1
  - patsy=1.0.1
  - pcre2=10.42
  - pillow=11.1.0
  - pip=25.0
  - pixman=0.40.0
  - ply=3.11
  - py-xgboost=2.0.3
  - py4j=0.10.9.7
  - pybind11-abi=4
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyqt6-sip=13.9.1
  - python=3.9.21
  - python-blosc=1.10.6
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytz=2024.1
  - qt-main=5.15.2
  - readline=8.2
  - regex=2024.11.6
  - scipy=1.13.1
  - seaborn=0.13.2
  - setuptools=75.8.0
  - shap=0.46.0
  - sip=6.7.12
  - six=1.16.0
  - slicer=0.0.8
  - sqlite=3.45.3
  - statsmodels=0.14.4
  - tbb=2021.8.0
  - tesseract=5.2.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tomli=2.0.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - typing_extensions=4.12.2
  - tzdata=2025a
  - unicodedata2=15.1.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - xcb-util-cursor=0.1.4
  - xgboost=2.0.3
  - xz=5.6.4
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - anyio==4.8.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.4
      - attrs==25.1.0
      - babel==2.17.0
      - beautifulsoup4==4.13.3
      - bleach==6.2.0
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - comm==0.2.2
      - debugpy==1.8.13
      - decorator==5.2.1
      - defusedxml==0.7.1
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.17.0
      - flatbuffers==25.2.10
      - fqdn==1.5.1
      - fsspec==2025.3.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - idna==3.10
      - ipykernel==6.29.5
      - ipython==8.18.1
      - isoduration==20.11.0
      - jax==0.4.30
      - jaxlib==0.4.30
      - jedi==0.19.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - matplotlib-inline==0.1.7
      - mediapipe==0.10.11
      - mistune==3.1.2
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - opencv-contrib-python==4.11.0.86
      - opt-einsum==3.4.0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - platformdirs==4.3.6
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - protobuf==3.20.3
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pygments==2.19.1
      - python-json-logger==3.3.0
      - pyyaml==6.0.2
      - pyzmq==26.2.1
      - referencing==0.36.2
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.23.1
      - scikit-learn==1.4.1.post1
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - sniffio==1.3.1
      - sounddevice==0.5.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - sympy==1.13.1
      - terminado==0.18.1
      - tinycss2==1.4.0
      - torch==2.6.0
      - traitlets==5.14.3
      - triton==3.2.0
      - types-python-dateutil==2.9.0.20241206
      - uri-template==1.3.0
      - urllib3==2.3.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
